<?php

namespace AppBundle\Repository;

/**
 * SamaritaineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SamaritaineRepository extends \Doctrine\ORM\EntityRepository
{

}
